<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Car_brand extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Car_brand_model');
 } 
 /*
* Listing of car_brand
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['car_brand'] = $this->Car_brand_model->get_all_car_brand();
      $data['_view'] = 'car_brand/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Car_brand Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new car_brand
  */
 function add()
 {  
try{
      $params = array(
       'brand_name'=> $this->input->post('brand_name'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       $this->form_validation->set_rules('brand_name','Brand name','required');
        if($this->form_validation->run())  
        {  
            $brand_id= $this->Car_brand_model->add_car_brand($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('car_brand/index');
        }
        else
        { 
           $data['_view'] = 'car_brand/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Car_brand Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a car_brand
 */
 public function edit($brand_id)
 {   
  try{
   $data['car_brand'] = $this->Car_brand_model->get_car_brand($brand_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['car_brand']['brand_id']))
      {
        $params = array(
           'brand_name'=> $this->input->post('brand_name'),
        );
               $this->form_validation->set_rules('brand_name','brand_name','required');
         if($this->form_validation->run())  
           {  
           $this->Car_brand_model->update_car_brand($brand_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('car_brand/index');
           }
           else
          {
              $data['_view'] = 'car_brand/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The car_brand you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Car_brand Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting car_brand
  */
  function remove($brand_id)
   {
    try{
      $car_brand = $this->Car_brand_model->get_car_brand($brand_id);
  // check if the car_brand exists before trying to delete it
       if(isset($car_brand['brand_id']))
       {
         $this->Car_brand_model->delete_car_brand($brand_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('car_brand/index');
       }
       else
       show_error('The car_brand you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Car_brand Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a car_brand
 */
 public function view_more($brand_id)
 {   
try{
   $data['car_brand'] = $this->Car_brand_model->get_car_brand($brand_id);
     if(isset($data['car_brand']['brand_id']))
      {
              $data['_view'] = 'car_brand/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The car_brand you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Car_brand Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of car_brand
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['car_brand'] = $this->Car_brand_model->get_all_car_brand_by_cat($column_name,$value_id);
      $data['_view'] = 'car_brand/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- car_brand
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Car_brand_model->update_car_brand($id,$params);
   $data['noof_page'] = 0;
  $data['car_brand'] = $this->Car_brand_model->get_all_car_brand();
  $this->load->view('car_brand/index',$data);
}
 }
