<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Car_detail extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Car_detail_model');
 } 
 /*
* Listing of car_detail
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['car_detail'] = $this->Car_detail_model->get_all_with_asso_car_detail();
      $data['_view'] = 'car_detail/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Car_detail Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new car_detail
  */
 function add()
 {  
try{
      $params = array(
       'type_id'=> $this->input->post('type_id'),
       'brand_id'=> $this->input->post('brand_id'),
       'ver_id'=> $this->input->post('ver_id'),
       'car_name'=> $this->input->post('car_name'),
       'car_detail'=> $this->input->post('car_detail'),
       'car_price'=> $this->input->post('car_price'),
       'created_by'=> $this->input->post('created_by'),
       'update_at'=> $this->input->post('update_at'),
       'created_date'=> $this->input->post('created_date'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
        $foldername='car_image';
        $fileuploaddire='./resource/'.$foldername;
        $directory=base_url('resource/').$foldername;
        if (!is_dir($fileuploaddire)) {
         mkdir($fileuploaddire, 0777, true);
        }
        $car_image="";
        if (!empty($_FILES['car_image']['name']))
        { 
            $filename =time().$_FILES['car_image']['name'];
            $car_image = str_replace(' ','_',$filename);
            $config['file_name'] = $car_image; 
            $config['upload_path']=$fileuploaddire;
            $config['allowed_types']='pdf|doc|docx|docs|jpg|jpeg|png|';
             $config['max_length']='100000';
            $this->upload->initialize($config);
            if(!$this->upload->do_upload('car_image'))
            {
                $error =$this->upload->display_errors();
                                                    // print_r($error);
                $msg='File Can not Upload ..Please upload pdf |doc |docs|jpg|jpeg|png  type only and Maximum file size 25MB '.$error;
                $this->session->set_flashdata('car_image',$msg);
                 $this->form_validation->set_rules('car_image',$msg,'required');
            }
            else 
            {
            }
        }
        else
        {
               //$this->form_validation->set_rules('car_image','file','required');
                $this->session->set_flashdata('car_image','File required');
        }
        $params['car_image'] =$car_image;
       $this->form_validation->set_rules('type_id','Type id','required');
       $this->form_validation->set_rules('brand_id','Brand id','required');
       $this->form_validation->set_rules('ver_id','Ver id','required');
       $this->form_validation->set_rules('car_name','Car name','required');
       $this->form_validation->set_rules('car_detail','Car detail','required');
       $this->form_validation->set_rules('car_price','Car price','required');
       $this->form_validation->set_rules('created_by','Created by','required');
       $this->form_validation->set_rules('update_at','Update at','required');
       $this->form_validation->set_rules('created_date','Created date','required');
        if($this->form_validation->run())  
        {  
            $car_id= $this->Car_detail_model->add_car_detail($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('car_detail/index');
        }
        else
        { 
         $this->load->model('Car_type_model');
         $data['all_car_type'] = $this->Car_type_model->get_all_car_type(); 
         $this->load->model('Car_brand_model');
         $data['all_car_brand'] = $this->Car_brand_model->get_all_car_brand(); 
         $this->load->model('Car_version_model');
         $data['all_car_version'] = $this->Car_version_model->get_all_car_version(); 
           $data['_view'] = 'car_detail/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Car_detail Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a car_detail
 */
 public function edit($car_id)
 {   
  try{
   $data['car_detail'] = $this->Car_detail_model->get_car_detail($car_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['car_detail']['car_id']))
      {
        $params = array(
           'type_id'=> $this->input->post('type_id'),
           'brand_id'=> $this->input->post('brand_id'),
           'ver_id'=> $this->input->post('ver_id'),
           'car_name'=> $this->input->post('car_name'),
           'car_detail'=> $this->input->post('car_detail'),
           'car_price'=> $this->input->post('car_price'),
           'created_by'=> $this->input->post('created_by'),
           'update_at'=> $this->input->post('update_at'),
           'created_date'=> $this->input->post('created_date'),
        );
      $foldername='car_image';
      $fileuploaddire='./resource/'.$foldername;
      $directory=base_url('resource/').$foldername;
      if (!is_dir($fileuploaddire)) {
         mkdir($fileuploaddire, 0777, true);
      }
      $car_image="";
      if (!empty($_FILES['car_image']['name']))
      { 
          $filename =time().$_FILES['car_image']['name'];
          $car_image = str_replace(' ','_',$filename);
          $config['file_name'] = $car_image; 
          $config['upload_path']=$fileuploaddire;
          $config['allowed_types']='pdf|doc|docx|docs|jpg|jpeg|png|';
          $config['max_length']='100000';
          $this->upload->initialize($config);
          if(!$this->upload->do_upload('car_image'))
          {
              $error =$this->upload->display_errors();
                                                    // print_r($error);
              $msg='File Can not Upload ..Please upload pdf |doc |docs|jpg|jpeg|png  type only and Maximum file size 25MB '.$error;
              $this->session->set_flashdata('car_image',$msg);
                $this->form_validation->set_rules('car_image',$msg,'required');
              }
              else 
              {
          $pathn=FCPATH.'resource/car_image/'.$data['car_detail']['car_image'];
         if(is_file($pathn))
           unlink($pathn);   
                $params['car_image'] =$car_image;
              }
       }
       else
       {
        }
               $this->form_validation->set_rules('type_id','type_id','required');
               $this->form_validation->set_rules('brand_id','brand_id','required');
               $this->form_validation->set_rules('ver_id','ver_id','required');
               $this->form_validation->set_rules('car_name','car_name','required');
               $this->form_validation->set_rules('car_image','car_image','required');
               $this->form_validation->set_rules('car_detail','car_detail','required');
               $this->form_validation->set_rules('car_price','car_price','required');
               $this->form_validation->set_rules('created_by','created_by','required');
               $this->form_validation->set_rules('update_at','update_at','required');
               $this->form_validation->set_rules('created_date','created_date','required');
         if($this->form_validation->run())  
           {  
           $this->Car_detail_model->update_car_detail($car_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('car_detail/index');
           }
           else
          {
             $this->load->model('Car_type_model');
             $data['all_car_type'] = $this->Car_type_model->get_all_car_type(); 
             $this->load->model('Car_brand_model');
             $data['all_car_brand'] = $this->Car_brand_model->get_all_car_brand(); 
             $this->load->model('Car_version_model');
             $data['all_car_version'] = $this->Car_version_model->get_all_car_version(); 
              $data['_view'] = 'car_detail/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The car_detail you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Car_detail Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting car_detail
  */
  function remove($car_id)
   {
    try{
      $car_detail = $this->Car_detail_model->get_car_detail($car_id);
  // check if the car_detail exists before trying to delete it
       if(isset($car_detail['car_id']))
       {
         $this->Car_detail_model->delete_car_detail($car_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
          $pathn=FCPATH.'resource/car_image/'.$car_detail['car_image'];
         if(is_file($pathn))
           unlink($pathn);   
           redirect('car_detail/index');
       }
       else
       show_error('The car_detail you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Car_detail Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a car_detail
 */
 public function view_more($car_id)
 {   
try{
   $data['car_detail'] = $this->Car_detail_model->get_car_detail($car_id);
     if(isset($data['car_detail']['car_id']))
      {
              $data['_view'] = 'car_detail/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The car_detail you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Car_detail Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of car_detail
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['car_detail'] = $this->Car_detail_model->get_all_with_asso_car_detail_by_cat($column_name,$value_id);
      $data['_view'] = 'car_detail/index';
      $this->load->view('layouts/main',$data);
}
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_type_id()
 {   
     $type_id= $this->input->post('value');
        $this->load->model('Car_type_model');
        $data['all_car_type'] = $this->Car_type_model->get_all_car_type(); 
      $car_detail = $this->Car_detail_model->get_all_with_asso_car_detail();
if(isset($data['all_car_type']) && $data['all_car_type']!=null)
                                              {
                                              foreach($data['all_car_type'] as $c){ 
      echo          "<option value='".$c['type_id']."'> ".$c['type_name']."</option>"; 
 } 
                                              }
                                              else{
                                                        echo '<tr>No data found</tr>';
                                              }
 } 
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_brand_id()
 {   
     $brand_id= $this->input->post('value');
        $this->load->model('Car_brand_model');
        $data['all_car_brand'] = $this->Car_brand_model->get_all_car_brand(); 
      $car_detail = $this->Car_detail_model->get_all_with_asso_car_detail();
if(isset($data['all_car_brand']) && $data['all_car_brand']!=null)
                                              {
                                              foreach($data['all_car_brand'] as $c){ 
      echo          "<option value='".$c['brand_id']."'> ".$c['brand_name']."</option>"; 
 } 
                                              }
                                              else{
                                                        echo '<tr>No data found</tr>';
                                              }
 } 
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_ver_id()
 {   
     $ver_id= $this->input->post('value');
        $this->load->model('Car_version_model');
        $data['all_car_version'] = $this->Car_version_model->get_all_car_version(); 
      $car_detail = $this->Car_detail_model->get_all_with_asso_car_detail();
if(isset($data['all_car_version']) && $data['all_car_version']!=null)
                                              {
                                              foreach($data['all_car_version'] as $c){ 
      echo          "<option value='".$c['ver_id']."'> ".$c['ver_name']."</option>"; 
 } 
                                              }
                                              else{
                                                        echo '<tr>No data found</tr>';
                                              }
 } 
 /*
* get search values by column- car_detail
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Car_detail_model->update_car_detail($id,$params);
   $data['noof_page'] = 0;
  $data['car_detail'] = $this->Car_detail_model->get_all_with_asso_car_detail();
  $this->load->view('car_detail/index',$data);
}
 }
