<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Car_version extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Car_version_model');
 } 
 /*
* Listing of car_version
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['car_version'] = $this->Car_version_model->get_all_with_asso_car_version();
      $data['_view'] = 'car_version/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Car_version Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new car_version
  */
 function add()
 {  
try{
      $params = array(
       'brand_id'=> $this->input->post('brand_id'),
       'ver_name'=> $this->input->post('ver_name'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       $this->form_validation->set_rules('brand_id','Brand id','required');
       $this->form_validation->set_rules('ver_name','Ver name','required');
        if($this->form_validation->run())  
        {  
            $ver_id= $this->Car_version_model->add_car_version($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('car_version/index');
        }
        else
        { 
         $this->load->model('Car_brand_model');
         $data['all_car_brand'] = $this->Car_brand_model->get_all_car_brand(); 
           $data['_view'] = 'car_version/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Car_version Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a car_version
 */
 public function edit($ver_id)
 {   
  try{
   $data['car_version'] = $this->Car_version_model->get_car_version($ver_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['car_version']['ver_id']))
      {
        $params = array(
           'brand_id'=> $this->input->post('brand_id'),
           'ver_name'=> $this->input->post('ver_name'),
        );
               $this->form_validation->set_rules('brand_id','brand_id','required');
               $this->form_validation->set_rules('ver_name','ver_name','required');
         if($this->form_validation->run())  
           {  
           $this->Car_version_model->update_car_version($ver_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('car_version/index');
           }
           else
          {
             $this->load->model('Car_brand_model');
             $data['all_car_brand'] = $this->Car_brand_model->get_all_car_brand(); 
              $data['_view'] = 'car_version/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The car_version you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Car_version Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting car_version
  */
  function remove($ver_id)
   {
    try{
      $car_version = $this->Car_version_model->get_car_version($ver_id);
  // check if the car_version exists before trying to delete it
       if(isset($car_version['ver_id']))
       {
         $this->Car_version_model->delete_car_version($ver_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('car_version/index');
       }
       else
       show_error('The car_version you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Car_version Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a car_version
 */
 public function view_more($ver_id)
 {   
try{
   $data['car_version'] = $this->Car_version_model->get_car_version($ver_id);
     if(isset($data['car_version']['ver_id']))
      {
              $data['_view'] = 'car_version/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The car_version you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Car_version Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of car_version
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['car_version'] = $this->Car_version_model->get_all_with_asso_car_version_by_cat($column_name,$value_id);
      $data['_view'] = 'car_version/index';
      $this->load->view('layouts/main',$data);
}
  /*
  * get get_search_values_byclms by id
 */
 public function get_search_values_by_brand_id()
 {   
     $brand_id= $this->input->post('value');
        $this->load->model('Car_brand_model');
        $data['all_car_brand'] = $this->Car_brand_model->get_all_car_brand(); 
      $car_version = $this->Car_version_model->get_all_with_asso_car_version();
if(isset($data['all_car_brand']) && $data['all_car_brand']!=null)
                                              {
                                              foreach($data['all_car_brand'] as $c){ 
      echo          "<option value='".$c['brand_id']."'> ".$c['brand_name']."</option>"; 
 } 
                                              }
                                              else{
                                                        echo '<tr>No data found</tr>';
                                              }
 } 
 /*
* get search values by column- car_version
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Car_version_model->update_car_version($id,$params);
   $data['noof_page'] = 0;
  $data['car_version'] = $this->Car_version_model->get_all_with_asso_car_version();
  $this->load->view('car_version/index',$data);
}
 }
