<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Car_type extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Car_type_model');
 } 
 /*
* Listing of car_type
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['car_type'] = $this->Car_type_model->get_all_car_type();
      $data['_view'] = 'car_type/index';
      $this->load->view('layouts/main',$data);
    } catch (Exception $ex) {
      throw new Exception('Car_type Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new car_type
  */
 function add()
 {  
try{
      $params = array(
       'type_name'=> $this->input->post('type_name'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       $this->form_validation->set_rules('type_name','Type name','required');
        if($this->form_validation->run())  
        {  
            $type_id= $this->Car_type_model->add_car_type($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('car_type/index');
        }
        else
        { 
           $data['_view'] = 'car_type/add';
            $this->load->view('layouts/main',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Car_type Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a car_type
 */
 public function edit($type_id)
 {   
  try{
   $data['car_type'] = $this->Car_type_model->get_car_type($type_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['car_type']['type_id']))
      {
        $params = array(
           'type_name'=> $this->input->post('type_name'),
        );
               $this->form_validation->set_rules('type_name','type_name','required');
         if($this->form_validation->run())  
           {  
           $this->Car_type_model->update_car_type($type_id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('car_type/index');
           }
           else
          {
              $data['_view'] = 'car_type/edit';
              $this->load->view('layouts/main',$data);
          }
  }
  else
  show_error('The car_type you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Car_type Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting car_type
  */
  function remove($type_id)
   {
    try{
      $car_type = $this->Car_type_model->get_car_type($type_id);
  // check if the car_type exists before trying to delete it
       if(isset($car_type['type_id']))
       {
         $this->Car_type_model->delete_car_type($type_id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('car_type/index');
       }
       else
       show_error('The car_type you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Car_type Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a car_type
 */
 public function view_more($type_id)
 {   
try{
   $data['car_type'] = $this->Car_type_model->get_car_type($type_id);
     if(isset($data['car_type']['type_id']))
      {
              $data['_view'] = 'car_type/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The car_type you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Car_type Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of car_type
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['car_type'] = $this->Car_type_model->get_all_car_type_by_cat($column_name,$value_id);
      $data['_view'] = 'car_type/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- car_type
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Car_type_model->update_car_type($id,$params);
   $data['noof_page'] = 0;
  $data['car_type'] = $this->Car_type_model->get_all_car_type();
  $this->load->view('car_type/index',$data);
}
 }
