<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Car_type_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get car_type by type_id 
      */ 
      function get_car_type($type_id)
      {
        try{
           return $this->db->get_where('car_type',array('type_id'=>$type_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Car_type_model Model : Error in get_car_type function - ' . $ex);
           }  
      }
      /*
        * Get car_type by  column name
      */ 
      function get_car_typebyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('car_type',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Car_type_model Madel : Error in get_car_typebyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All car_type count 
      */ 
      function get_all_car_type_count()
      {
        try{
           $this->db->from('car_type');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in get_all_car_type_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join car_typecount 
      */ 
      function get_all_with_asso_car_type()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in get_all_with_asso_car_type function - ' . $ex);
           }  
      }
      /*
          * Get all car_type 
      */ 
      function get_all_car_type($params = array())
      {
        try{
              $this->db->order_by('type_id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('car_type')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in get_all_car_type function - ' . $ex);
           }  
      } 
      /*
         * function to add new car_type 
      */
      function add_car_type($params)
      {
        try{
          $this->db->insert('car_type',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in add_car_type function - ' . $ex);
           }  
      }
      /* 
          * function to update car_type 
      */
      function update_car_type($type_id,$params)
      {
        try{
            $this->db->where('type_id',$type_id);
        return $this->db->update('car_type',$params);
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in update_car_type function - ' . $ex);
           }  
       }
     /* 
          * function to delete car_type 
      */
       function delete_car_type($type_id)
       {
        try{
             return $this->db->delete('car_type',array('type_id'=>$type_id));
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in delete_car_type function - ' . $ex);
           }  
       }
      /*
        * Get car_type by  column name where not in particular id
      */ 
      function get_car_typebyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('type_id!=', $where_cond);
           return $this->db->get_where('car_type',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in get_car_typebyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join car_typecount 
      */ 
      function get_all_with_asso_car_type_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in get_all_with_asso_car_type_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all car_type_by_cat 
      */ 
      function get_all_car_type_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('type_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('car_type')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Car_type_model model : Error in get_all_car_type_by_cat function - ' . $ex);
           }  
      } 
 }
