<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Car_detail_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get car_detail by car_id 
      */ 
      function get_car_detail($car_id)
      {
        try{
           return $this->db->get_where('car_detail',array('car_id'=>$car_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model Model : Error in get_car_detail function - ' . $ex);
           }  
      }
      /*
        * Get car_detail by  column name
      */ 
      function get_car_detailbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('car_detail',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model Madel : Error in get_car_detailbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All car_detail count 
      */ 
      function get_all_car_detail_count()
      {
        try{
           $this->db->from('car_detail');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in get_all_car_detail_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join car_detailcount 
      */ 
      function get_all_with_asso_car_detail()
      {
        try{
           $this->db->select('*');
           $this->db->from('car_detail a  ' );
            $this->db->join('car_type b', 'b.type_id=a. type_id','left');
            $this->db->join('car_brand c', 'c.brand_id=a. brand_id','left');
            $this->db->join('car_version d', 'd.ver_id=a. ver_id','left');
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in get_all_with_asso_car_detail function - ' . $ex);
           }  
      }
      /*
          * Get all car_detail 
      */ 
      function get_all_car_detail($params = array())
      {
        try{
              $this->db->order_by('car_id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('car_detail')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in get_all_car_detail function - ' . $ex);
           }  
      } 
      /*
         * function to add new car_detail 
      */
      function add_car_detail($params)
      {
        try{
          $this->db->insert('car_detail',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in add_car_detail function - ' . $ex);
           }  
      }
      /* 
          * function to update car_detail 
      */
      function update_car_detail($car_id,$params)
      {
        try{
            $this->db->where('car_id',$car_id);
        return $this->db->update('car_detail',$params);
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in update_car_detail function - ' . $ex);
           }  
       }
     /* 
          * function to delete car_detail 
      */
       function delete_car_detail($car_id)
       {
        try{
             return $this->db->delete('car_detail',array('car_id'=>$car_id));
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in delete_car_detail function - ' . $ex);
           }  
       }
      /*
        * Get car_detail by  column name where not in particular id
      */ 
      function get_car_detailbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('car_id!=', $where_cond);
           return $this->db->get_where('car_detail',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in get_car_detailbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join car_detailcount 
      */ 
      function get_all_with_asso_car_detail_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
           $this->db->select('*');
           $this->db->from('car_detail a  ' );
              //$this->db->where($column_name, $value_id);
            $this->db->join('car_type b', 'b.type_id=a. type_id','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('car_brand c', 'c.brand_id=a. brand_id','left');
              $this->db->where('a.'.$column_name, $value_id);
            $this->db->join('car_version d', 'd.ver_id=a. ver_id','left');
              $this->db->where('a.'.$column_name, $value_id);
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in get_all_with_asso_car_detail_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all car_detail_by_cat 
      */ 
      function get_all_car_detail_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('car_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('car_detail')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Car_detail_model model : Error in get_all_car_detail_by_cat function - ' . $ex);
           }  
      } 
 }
