<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Car_type extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Car_type_model');
 } 
 /*
* Listing of car_type
 */
public function get_all_post()
{
  try{
  $data['car_type'] = $this->Car_type_model->get_all_car_type();
     if($data['car_type'] && $data['car_type']!=null){
       $car_type_ar = array();
       foreach($data['car_type'] as $c)
       {
       $c_ar = array();
       $c_ar['type_name'] = $c['type_name'];
       $car_type_ar[] = $c_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $car_type_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Car_type controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new car_type
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'type_name'=> $this->input->post('type_name'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
  if(isset($_POST['type_name']) && $_POST['type_name'] == '' || !isset($_POST['type_name']))
                         $this->response(array('status' => 400,'message' => 'type_name is require'), REST_Controller::HTTP_OK);
        if($this->form_validation->run())  
        {  
            $type_id= $this->Car_type_model->add_car_type($params);
   $data['car_type'] = $this->Car_type_model->get_car_type($type_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Car_type controller_name : Error in new car_type function - ' . $ex);
       }  
 }  
  /*
  * Editing a car_type
 */
  function edit_post($type_id)
 {   
  try{
   $data['car_type'] = $this->Car_type_model->get_car_type($type_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['car_type']['type_id']))
      {
        $params = array(
           'type_name'=> $this->input->post('type_name'),
        );
           $this->response(array('status' => 400,'message' => 'type_name required'), REST_Controller::HTTP_OK);
         if($this->form_validation->run())  
           {  
           $this->Car_type_model->update_car_type($type_id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $type_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $type_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Car_type controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting car_type
  */
  function remove_post($type_id)
   {
  try{
      $car_type = $this->Car_type_model->get_car_type($type_id);
  // check if the car_type exists before trying to delete it
       if(isset($car_type['type_id']))
       {
         $this->Car_type_model->delete_car_type($type_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $type_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $type_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Car_type controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
