<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Car_brand extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Car_brand_model');
 } 
 /*
* Listing of car_brand
 */
public function get_all_post()
{
  try{
  $data['car_brand'] = $this->Car_brand_model->get_all_car_brand();
     if($data['car_brand'] && $data['car_brand']!=null){
       $car_brand_ar = array();
       foreach($data['car_brand'] as $c)
       {
       $c_ar = array();
       $c_ar['brand_name'] = $c['brand_name'];
       $car_brand_ar[] = $c_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $car_brand_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Car_brand controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new car_brand
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'brand_name'=> $this->input->post('brand_name'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
  if(isset($_POST['brand_name']) && $_POST['brand_name'] == '' || !isset($_POST['brand_name']))
                         $this->response(array('status' => 400,'message' => 'brand_name is require'), REST_Controller::HTTP_OK);
        if($this->form_validation->run())  
        {  
            $brand_id= $this->Car_brand_model->add_car_brand($params);
   $data['car_brand'] = $this->Car_brand_model->get_car_brand($brand_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Car_brand controller_name : Error in new car_brand function - ' . $ex);
       }  
 }  
  /*
  * Editing a car_brand
 */
  function edit_post($brand_id)
 {   
  try{
   $data['car_brand'] = $this->Car_brand_model->get_car_brand($brand_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['car_brand']['brand_id']))
      {
        $params = array(
           'brand_name'=> $this->input->post('brand_name'),
        );
           $this->response(array('status' => 400,'message' => 'brand_name required'), REST_Controller::HTTP_OK);
         if($this->form_validation->run())  
           {  
           $this->Car_brand_model->update_car_brand($brand_id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $brand_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $brand_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Car_brand controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting car_brand
  */
  function remove_post($brand_id)
   {
  try{
      $car_brand = $this->Car_brand_model->get_car_brand($brand_id);
  // check if the car_brand exists before trying to delete it
       if(isset($car_brand['brand_id']))
       {
         $this->Car_brand_model->delete_car_brand($brand_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $brand_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $brand_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Car_brand controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
